### ISSUE TITLE
Rename Tooltip / Chest name does not work

### ISSUE THREAD

**Issue by BenRoe** [Zaicon/InfiniteChestsV2#11]
Hello,
if i rename the chest and i hover over it, it's still "chest". If i open the chest the new name is shown in the chest menu.
Is that a feature or bug?

**Comment by aylinni-empyrea** [comment]
https://github.com/Zaicon/InfiniteChestsV2#things-this-plugin-will-not-do-as-of-now

> Chest name support. Chest names are stored in tile data, which would be very costly to implement.

**Comment by BenRoe** [comment]
ok thank you for the clarification.
