### ISSUE TITLE
Unhandled exception caused TSAPI stopped during running game

### ISSUE THREAD

**Issue by mistzzt** [Zaicon/InfiniteChestsV2#3]
Sad. How can I convert chest in db to the vanilla map file?

![issue](https://cloud.githubusercontent.com/assets/12794966/18872147/87f30612-84eb-11e6-85a8-004541e971c1.png)

**Comment by mistzzt** [comment]
This plugin is not able to run here at all. After initialization completed, the exception would occur with the crash of TSAPI.

**Comment by Zaicon** [comment]
Could you give me more details? What were you doing when it crashed? Does this happen with different maps?

**Comment by mistzzt** [comment]
After the server started, the exception will occur automatically as someone joined the game. I havent tested the plugin with different maps

**Comment by Zaicon** [comment]
Would you mind uploading the map here (or PM it to me on tShock) so that I can test it?

**Comment by mistzzt** [comment]
alright, it would not occur now.
but i dont have the map file which caused exception
