### ISSUE TITLE
/prunechests will remove (almost) all chest

### ISSUE THREAD

**Issue by OnsenManju** [Zaicon/InfiniteChestsV2#4]
![prunechests](https://cloud.githubusercontent.com/assets/16373401/19798690/9a1238ae-9d2d-11e6-8b4b-f49f50bd9364.png)
It will be caused due to this query:
https://github.com/Zaicon/InfiniteChestsV2/blob/master/InfChests/DB.cs#L378
That reads "enumerate if one of its slots is empty".

Probably that should be, for example:
`string query = $"SELECT ChestID FROM ChestItems WHERE WorldID = {Main.worldID} GROUP BY ChestID HAVING MIN(Type) = 0 AND MAX(Type) = 0";
`
That means "show its id if all slot is empty for each chest".

And also, at line 403 is like this:
`query = $"DELETE FROM ChestItems WHERE WorldID = {Main.worldID} AND ChestID IN ({string.Join(",", chestIDs)})";`
(Sorry I didn't confirm them actually)

I'm not sure whether this issue  is related to that post though.
https://tshock.co/xf/index.php?threads/infinitechestsv2.4795/page-2#post-47100

**Comment by Kojirremer** [comment]
As I stated on that post, it will always crash in my case, but I did see all (non-empty) chest in my screen being uprooted before getting the crash notification.

**Comment by Zaicon** [comment]
Fixed in https://github.com/Zaicon/InfiniteChestsV2/commit/71daf9a0ba2799ed004cafdca6aef0ba2fe02ee6.
